on:
  issues:
    types: [opened]
jobs:
  Add_New_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
      uses: actions/add-to-project@main
      with:
        action-token: "${{ secrets.TOKEN }}"
        project-url: "https://github.com/users/eag1/projects/1"
        column-name: "todo"
